config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  resources 'weather' , only: [:index,:create,:show]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
	require 'open-uri'
	require 'json'

	def index
	end


	def create
		#Capture the response from the form
		cordinates= Geocoder.coordinates(params[:city_input])
		#Stop if an incorrect location is given
		if cordinates.nil?
			flash.now[:notice] = "Location does not exist"
			redirect_to :back
			return
		end
		
		#Store Latitude and Longitude
		lat= cordinates[0].to_s
		lng= cordinates[1].to_s
		key="72ee8bab77d416d99b868bba45f4c24e"
		#URI to Open
		uri = "http://api.openweathermap.org/data/2.5/forecast/daily?lat="+lat+"&lon="+lng+"&cnt=16&mode=json&appid="+key
		#Open the URI and Read contents 
		response = open(uri).read
		#Parse JSON Response
		totalWeather = JSON.parse(response)
		#Array of days
		@dayArray = []
		totalWeather['list'].each do |i|
			#Weather Hash for each day
			weatherDay = Hash.new('n/a')
				#weatherDay["humidity"] = i['humidity'].to_s
				weatherDay["day"] = Time.at(i['dt']).to_datetime.strftime("%a").to_s
				weatherDay["date"] = Time.at(i['dt']).to_datetime.strftime("%d").to_s
				weatherDay["month"] = Time.at(i['dt']).to_datetime.strftime("%b").to_s
				weatherDay["main"] = i['weather'][0]['main'].to_s
				weatherDay["tempDay"] = i['temp']['day'].to_s
				weatherDay["tempMin"] = i['temp']['min'].to_s
				weatherDay["desc"] = i['weather'][0]['description'].to_s
			@dayArray << weatherDay
		end
		session[:array] = @dayArray
		flash[:notice] = "location exists"
		render :index
	end

	def show()
		#Specify the specific day from the session in the array
		@weatherForDay = session[:array][params[:id].to_i]
		puts "this is a test" + @weatherForDay.to_s
		respond_to do |format|
			format.js
		end

	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<%= render "shared/search" %>

app/views/shared/_results.html.erb
<div class="owl-carousel">
	<% count = 0 %>
	<%@dayArray.each do |day| %>
		<!-- crete a link based on the count-->
		<%= link_to weather_path(count), :remote => true do %>
			<div class="col-md-2 panel" id="<%= count %>">
					<span class='date'>Date: <%= day['day'] %> <%= day['date']%> <%= day['month']%> </span>
					<span class='main'>Weather: <%= day['main']%> </span>
			</div>
			<% count += 1%>
		<% end %>
	<% end %>

</div>

<div id="info">
	Temp Day:<div id="tempDay"></div></br>
	Temp Min:<div id="tempMin"></div></br>
</div>

app/views/shared/_search.html.erb
<script src="http://maps.googleapis.com/maps/api/js?libraries=places"></script>

<div class="header">
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4">
			<%= form_tag 'weather' do %>
				<%= label_tag(:form_label,'Enter City',class: 'label') %>
				<%= text_field_tag(:city_input,nil,placeholder: '  Enter a city') %>
		</div>
		<div class="col-md-4"></div>
	</div>
	<div class="row">
		<div class="col-md-5"></div>
		<div class="col-md-2">
				<%= button_tag('Search', id: 'form_submit', class: 'button') %>
			<% end %>
		</div>
		<div class="col-md-5"></div>
	</div>
</div>

app/views/weather/index.html.erb
<%= render "shared/search" %>
<div class="alertArea">
	<% if flash[:notice] %>
	<div class="notice">
		<%= flash[:notice] %>
	</div>
	<script>$(".notice").animate({opacity: 0}, 2000	);</script>
	<% end %>
</div>
<% if @dayArray.present? %>
	<%= render "shared/results" %>
<% end %>

app/views/weather/show.js.erb
$(document).ready(function(){

  $("#tempDay").text("<%= @weatherForDay['tempDay'] %>");
  $("#tempMin").text("<%= @weatherForDay['tempMin'] %>");

});